### ISSUE TITLE
Whether can customise the html report file for each executed feature file?

### ISSUE THREAD

**Issue by neil-liao-dragon** [damianszczepanik/cucumber-reporting#961] opened 2020-08-17 07:34 UTC
Currently the generated report file for each feature file is like "report-feature_2968571909.html". But I want it like "report-feature_**featureFileName**_2968571909.html". does this plugin support this?

**Comment by damianszczepanik** [comment] 2020-08-17 20:17
Duplicate of https://github.com/jenkinsci/cucumber-reports-plugin/issues/372

**Closed by damianszczepanik** 2020-08-17 20:17 UTC
