### ISSUE TITLE
ParameterizedMessage ClassNotFoundException is thrown in 3.2.0 and 3.3.0

### ISSUE THREAD

**Issue by pcalouche** [damianszczepanik/cucumber-reporting#585] opened 2017-01-02 15:23 UTC
Great plugin by the way.  I noticed when going from 3.1.0 to 3.2.0 this exception is thrown.  Reports still generate fine from what I can tell.  Issue is also in 3.3.0.

> [INFO] 
[INFO] --- maven-cucumber-reporting:3.2.0:generate (execution) @ awtf-core ---
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
[INFO] About to generate Cucumber report.
[INFO] 
[INFO] --- maven-install-plugin:2.4:install (default-install) @ awtf-core ---
[INFO] Installing C:\Users\Philip Calouche\Documents\Projects\awtf\awtf-core\target\awtf-core-2.0.1.jar to C:\Users\Philip Calouche\.m2\repository\com\pcalouche\awtf-core\2.0.1\awtf-core-2.0.1.jar
[INFO] Installing C:\Users\Philip Calouche\Documents\Projects\awtf\awtf-core\pom.xml to C:\Users\Philip Calouche\.m2\repository\com\pcalouche\awtf-core\2.0.1\awtf-core-2.0.1.pom
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20.019 s
[INFO] Finished at: 2017-01-02T10:20:52-05:00
[INFO] Final Memory: 30M/410M
[INFO] ------------------------------------------------------------------------
Exception in thread "pool-2-thread-1" java.lang.NoClassDefFoundError: org/apache/logging/log4j/message/ParameterizedMessage
	at org.apache.logging.log4j.message.ParameterizedNoReferenceMessageFactory.newMessage(ParameterizedNoReferenceMessageFactory.java:104)
	at org.apache.logging.log4j.message.AbstractMessageFactory.newMessage(AbstractMessageFactory.java:75)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:2010)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1884)
	at org.apache.logging.log4j.spi.AbstractLogger.error(AbstractLogger.java:793)
	at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.run(DefaultShutdownCallbackRegistry.java:76)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.message.ParameterizedMessage
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
	... 7 more

**Comment by damianszczepanik** [comment] 2017-01-02 22:37
Duplicate of #562 - will be fixed with next release

**Closed by damianszczepanik** 2017-01-02 22:37 UTC
