### ISSUE TITLE
Issues generating reports from jenkins - Problems parsing JSON

### ISSUE THREAD

**Issue by bdesim2** [damianszczepanik/cucumber-reporting#315] opened 2016-01-25 20:07 UTC
Hello,

I am trying to use this Jenkins plugin to generate the pretty html reports from my cucumber tests.  I am using ruby to develop the tests and am following the instructions given in this repo. The error i am getting isattached below...It looks like its having issues parsing the JSON.  The interesting thing is the standalone version of this project works 100% with these same tests. For some reason the Jenkins server does not like the format of the JSON.  I have also attached the JSON file that i am using to set this up i attached it as a text file due to website restrictions

Hopefully someone can shed some light on this issue.

Thanks in Advance,
Brian

[test.txt](https://github.com/damianszczepanik/cucumber-reporting/files/103847/test.txt)
![error](https://cloud.githubusercontent.com/assets/16886269/12562831/cbc114f6-c36c-11e5-8639-2c94538a8b18.PNG)

**Comment by damianszczepanik** [comment] 2016-01-25 20:50
The reason of this problem might be that Jenkins is trying to parse more json files you want/expect. Check attached logs and confirm that all json files listed are cucumber reports.

**Comment by bdesim2** [comment] 2016-01-25 20:52
I have checked that. there is only one file and the plugin is only recognizing that one single file.

**Comment by damianszczepanik** [comment] 2016-01-25 22:01
Logs above say something different

**Comment by bdesim2** [comment] 2016-01-25 22:09
Here is one of the JSON files listed above. When running with just the one file i get the same error.

[{"uri":"features/selenium.feature","id":"test","keyword":"Feature","name":"test","description":"","line":1,"elements":[{"id":"test;test1","keyword":"Scenario","name":"test1","description":"","line":2,"type":"scenario","steps":[{"keyword":"Given ","name":"We are using selenium to test with chrome","line":3,"match":{"location":"features/step_definitions/selenium/selenium.rb:8"},"result":{"status":"passed","duration":1717150000}},{"keyword":"When ","name":"I navigate to \"http://www.google.com\"","line":4,"match":{"location":"selenium-cucumber-2.1.3/lib/selenium-cucumber/navigation_steps.rb:3"},"result":{"status":"passed","duration":1371137000}},{"keyword":"Then ","name":"I should see page title as \"Google\"","line":5,"match":{"location":"selenium-cucumber-2.1.3/lib/selenium-cucumber/assertion_steps.rb:4"},"result":{"status":"passed","duration":11001000}},{"keyword":"And ","name":"element having id \"lst-ib\" should be enabled","line":6,"match":{"location":"selenium-cucumber-2.1.3/lib/selenium-cucumber/assertion_steps.rb:31"},"result":{"status":"passed","duration":33003000}},{"keyword":"When ","name":"I enter \"hello world\" into input field having id \"lst-ib\"","line":7,"match":{"location":"selenium-cucumber-2.1.3/lib/selenium-cucumber/input_steps.rb:4"},"result":{"status":"passed","duration":82008000}},{"keyword":"And ","name":"I click on element having id \"lst-ib\"","line":8,"match":{"location":"selenium-cucumber-2.1.3/lib/selenium-cucumber/click_elements_steps.rb:4"},"result":{"status":"passed","duration":43005000}}],"after":[{"match":{"location":{"filepath":{"filename":"json_spec-1.1.4/lib/json_spec/cucumber.rb"},"lines":{"data":["5"]}}},"result":{"status":"passed","duration":0}}]}]}]

**Comment by tommywo** [comment] 2016-01-26 12:55
The issue is with location element in after hook.
@bdesim2 which cucumber version do you use?
```
"location": "selenium-cucumber-2.1.3/lib/selenium-cucumber/click_elements_steps.rb:4"
```
```
              "location": {
                "filepath": {
                  "filename": "json_spec-1.1.4/lib/json_spec/cucumber.rb"
                },
                "lines": {
                  "data": [
                    "5"
                  ]
                }
```

**Comment by bdesim2** [comment] 2016-01-26 14:11
I'm using Cucumber 2.3.2 which i believe is the latest version.  You are correct this does work if the after hook is removed. I need after hooks to function correctly however for my project. Should i try changing cucumber versions?

**Comment by bdesim2** [comment] 2016-01-26 18:06
I am running this jenkins job on a slave node and the report is generating on the master node. will this cause problems? It looks like its trying to find certain "locations" or "files" and it is failing at those points from within the report generator.

**Comment by damianszczepanik** [comment] 2016-01-26 19:29
This issue has been already reported. You are using cucumber but not jvm, Because the newest version is http://search.maven.org/#search|gav|1|g%3A%22info.cukes%22%20AND%20a%3A%22cucumber-jvm%22 :)

Duplicate of https://github.com/damianszczepanik/cucumber-reporting-jenkins/issues/132

**Closed by damianszczepanik** 2016-01-26 19:29 UTC

**Comment by tommywo** [comment] 2016-01-26 22:53
@bdesim2 can you share small example how to recreate this json?

**Comment by bdesim2** [comment] 2016-01-26 22:58
I am using ruby on rails and cucumber so i run the command:
```
cucumber -f json -o C:\<path>\cucumber.json
```
Then i have the jvm plugin looking at the above location for all *.json files

It finds the file from the test starts to generate the report and then I see the error above.

I was looking at the issue above and downgraded my cucumber version.  Unfortunately this did not work.  I also took out all my before and after hooks. This still didnt fix the issue. I wonder if the cucumber output formatter is doing something weird.
