### ISSUE TITLE
java.io.FileNotFoundException File name too long. For generated html

### ISSUE THREAD

**Issue by SirLenz0rlot** [damianszczepanik/cucumber-reporting#119] opened 2015-07-14 08:26 UTC
I noticed the original package/path is also included in the name of the html file.
In my case this makes it longer than 255 characters, so as soon I as try to open my report, I get an error-page

    Oops Something went wrong with <my build>

and the error message:

    java.io.FileNotFoundException: <package_names_plus_the_feature_file_makes_this_a_very_long_file_name>.html (File name too long)

A fix could be to limit the filename to (the last?) 255 characters or to nest in folders like the original feature file.

**Comment by damianszczepanik** [comment] 2015-07-15 05:30
I believe not. If you expect support follow my suggestion

**Comment by SirLenz0rlot** [comment] 2015-07-15 21:29
I'm sorry, but I don't understand what you are suggesting

**Comment by damianszczepanik** [comment] 2015-08-22 07:35
Package should not be included into file as long as it is not present in json file. If you meet such problem, share json file so I can analyze the problem and provide fix.

**Comment by damianszczepanik** [comment] 2015-12-07 21:27
No feedback, resolving this issue.

**Closed by damianszczepanik** 2015-12-07 21:27 UTC
Labels: bug

**Comment by SirLenz0rlot** [comment] 2016-09-20 08:01
@damianszczepanik 
Sorry, it took me a while to respond, the issue is still very revelant. I've attached a minimal JSON I can reproduce this with:

```json
[
  {
    "id": "the-id-of-my-feature",
    "uri": "/home/my/path/com/my/very/deep/package/where/my/features/exists/are/too/long/for/one/file/as/a/file/name/this_is_my_very_own_test_name.feature"
  }
]
```

Stack trace shown in output:

```
net.masterthought.cucumber.ValidationException: java.io.FileNotFoundException: ../../report/AcceptanceTests/cucumber-html-reports/-home-my-path-com-my-very-deep-package-where-my-features-exists-are-too-long-for-one-file-as-a-file-name-this_is_my_very_own_test_name-feature.html (File name too long)
	at net.masterthought.cucumber.generators.AbstractPage.generateReport(AbstractPage.java:72)
	at net.masterthought.cucumber.generators.AbstractPage.generatePage(AbstractPage.java:55)
	at net.masterthought.cucumber.ReportBuilder.generateAllPages(ReportBuilder.java:108)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:59)
	at <MY CALL TO THE BUILDER>
Caused by: java.io.FileNotFoundException: ../../report/AcceptanceTests

/cucumber-html-reports/-home-my-path-com-my-very-deep-package-where-my-features-exists-are-too-long-for-one-file-as-a-file-name-this_is_my_very_own_test_name-feature.html (File name too long)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.(FileOutputStream.java:232)
	at java.io.FileOutputStream.(FileOutputStream.java:182)
	at net.masterthought.cucumber.generators.AbstractPage.generateReport(AbstractPage.java:69)
	... 41 more
```

**Comment by SirLenz0rlot** [comment] 2016-09-20 08:19
@damianszczepanik is this enough information to reopen the issue?

**Comment by damianszczepanik** [comment] 2016-09-20 11:37
The cause has been reported and is not related to this plugin

**Comment by SirLenz0rlot** [comment] 2016-09-20 11:57
Can you link us to where it is reported?

https://github.com/damianszczepanik/cucumber-reporting/blob/5cfde3be3bb65b89a4c8c81776f720cd5e90d62a/src/main/java/net/masterthought/cucumber/json/Feature.java#L189
It's using the uri to generate a filename.
Since each OS (I think) has a file name length limitation, I tend to consider this fragile.

Is there a known workaround, except for changing my project package tree?
The only one I can think of, is to shorten the uri in the json output before calling this reporter.

**Comment by damianszczepanik** [comment] 2016-09-20 15:17
You can use https://github.com/damianszczepanik/silencio to  convert some nodes from json report

**Comment by SirLenz0rlot** [comment] 2016-09-21 07:15
Thanks, I decided to go for a simple regex-based replace script instead.
