### ISSUE TITLE
New feature: is it possible that add drillable link for failed scenarios?

### ISSUE THREAD

**Issue by idealivan** [damianszczepanik/cucumber-reporting#291] opened 2016-01-10 09:41 UTC
Usually it is needed to pay special attentions to failed scenarios.

is it possible to add drillable link for failed scenarios: `a page for specific feature that had been chosen, and just display all failed scenarios`.

Thanks
Cent Lui

**Comment by damianszczepanik** [comment] 2016-01-10 09:50
It is based on cucumber-jvm report so if you have such data in cucumber.json we can talk it over.

**Comment by damianszczepanik** [comment] 2016-04-17 20:40
Duplicate of #344

**Closed by damianszczepanik** 2016-04-17 20:40 UTC
