### ISSUE TITLE
Cucumber report not generating 

### ISSUE THREAD

**Issue by iam500** [damianszczepanik/cucumber-reporting#664] opened 2017-09-11 18:27 UTC
I am getting the following error when using the cumber-reporting plugin 3.10.0 with Jenkins 2.77 can you please suggest-
[CucumberReport] /fast/jenkins/jobs/ProjectName/builds/101/cucumber-html-reports/.cache/Test/target/cucumber.json
ERROR: Build step failed with exception
java.lang.IllegalArgumentException: No enum constant net.masterthought.cucumber.sorting.SortingMethod.
	at java.lang.Enum.valueOf(Enum.java:238)
	at net.masterthought.cucumber.sorting.SortingMethod.valueOf(SortingMethod.java:8)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:271)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:219)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:736)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:682)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1072)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:627)
	at hudson.model.Run.execute(Run.java:1754)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:542)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:419)

**Comment by damianszczepanik** [comment] 2017-09-11 19:27
Duplicate of  https://github.com/jenkinsci/cucumber-reports-plugin/issues/176

**Closed** 2017-09-24 18:03 UTC

**Comment by iam500** [comment] 2017-09-25 20:08
I upgraded to 3.10.3 but still getting the Sorting error. Please suggest

**Comment by damianszczepanik** [comment] 2017-09-26 12:19
Paste the stacktrace
