### ISSUE TITLE
JSON File Limit

### ISSUE THREAD

**Issue by NSsnowCorey** [damianszczepanik/cucumber-reporting#1117] opened 2023-11-13 16:48 UTC
When a json file beng passed to the library to build the html file is large, an error is being thrown.  The error is:
"is not a valid Cucumber report! String length (20054016) exceeds the maximum length (20000000) (through reference chain: java.lang.Object[][0]->net.masterthought.cucumber.json.Feature["elements"]->java.lang.Object[][3]->net.masterthought.cucumber.json.Element["steps"]->java.lang.Object[][2]->net.masterthought.cucumber.json.Step["doc_string"]->net.masterthought.cucumber.json.DocString["value"])"

**Comment by damianszczepanik** [comment] 2023-11-14 19:46
Duplicate of https://github.com/jenkinsci/cucumber-reports-plugin/issues/449

**Closed by damianszczepanik** 2023-11-14 19:46 UTC
