### ISSUE TITLE
2.4.0 broken on Jenkins 2.7, unable to see graphs, can't expand steps for old result and even do not see any result for recent execution.

### ISSUE THREAD

**Issue by mchoyal** [damianszczepanik/cucumber-reporting#473] opened 2016-06-14 06:20 UTC
Old reports are not showing any graphs and can't expand steps. While new reports does not show the graphs and steps. It shows message as "You have no features in your cucumber report" ... we have can see the JSON file is created there, but cucumber report is not generating.

**Comment by damianszczepanik** [comment] 2016-06-14 18:08
Duplicate of #472

**Closed by damianszczepanik** 2016-06-14 18:08 UTC
