### ISSUE TITLE
No more HTML tag interpretation in scenario.write()?

### ISSUE THREAD

**Issue by Ryxmedia** [damianszczepanik/cucumber-reporting#610] opened 2017-03-13 10:54 UTC
Hi,

just updated from 2.6.3 to 3.5.1 and suddenly my HTML tags won't get interpreted anymore, which I write in my scenario.write().
For example I use something like this to display it directly as a link in the output: 

`scenario.write("Error appeared on page: <a href=\"" + getCurrentUrl() + "\" target=\"_blank\">" + getTitle() + "<br />");`

Is there a trick to do something like this again?

**Comment by mpkorstanje** [comment] 2017-03-13 10:57
Yes, you can use

```java
scenario.embed(html.getBytes(), "text/html");
```

**Comment by Ryxmedia** [comment] 2017-03-13 11:56
Thanks for the fast reply, but that doesn't give me the results I had before.
Now it is still shown as plain text with HTML tags directly in the report.
I just get a link on the right side, where a new html page opens with the interpreted HTML code.

**Comment by damianszczepanik** [comment] 2017-03-13 20:27
Show me JSON file I believe it is supported quite well

**Comment by Ryxmedia** [comment] 2017-03-14 07:27
Java code part:
`	@After
	public void actionAfterFailedScenario(final Scenario scenario) {
		if (scenario.isFailed()) {
			String errorMessage = "<strong>Make this text bold</strong><br />";
			errorMessage = errorMessage.concat("<a href=\"http://i_am_a_link\">This is a link</a>");
			scenario.write(errorMessage);
			scenario.embed(errorMessage.getBytes(), "text/html");
		}
	}`

Same test run with 2.6.3:
![cucumber_2](https://cloud.githubusercontent.com/assets/9654470/23889859/6d4f9730-088f-11e7-9b43-8d118fe20372.png)

Run with 3.5.1:
![cucumber_3](https://cloud.githubusercontent.com/assets/9654470/23889858/6d36b2e2-088f-11e7-9145-514111f438cd.png)

JSON:
`[
  {
    "comments": [
      {
        "line": 1,
        "value": "#encoding: UTF-8"
      }
    ],
    "line": 3,
    "elements": [
      {
        "before": [
          {
            "result": {
              "duration": 4691379,
              "status": "passed"
            },
            "match": {
              "location": "OrganisationOverviewGlobalSteps.initializePageObjects(Scenario)"
            }
          }
        ],
        "line": 95,
        "name": "Example",
        "description": "",
        "id": "organisation---overview;example",
        "after": [
          {
            "result": {
              "duration": 4396089,
              "status": "passed"
            },
            "match": {
              "location": "NavigationSteps.actionAfterFailedScenario(Scenario)"
            }
          }
        ],
        "type": "scenario",
        "keyword": "Scenario",
        "steps": [
          {
            "result": {
              "duration": 4340648044,
              "error_message": "org.openqa.selenium.NoSuchElementException:...",
              "status": "failed"
            },
            "output": [
              "\u003cstrong\u003eMake this text bold\u003c/strong\u003e\u003cbr /\u003e\u003ca href\u003d\"http://i_am_a_link\"\u003eThis is a link\u003c/a\u003e"
            ],
            "embeddings": [
              {
                "data": "PHN0cm9uZz5NYWtlIHRoaXMgdGV4dCBib2xkPC9zdHJvbmc+PGJyIC8+PGEgaHJlZj0iaHR0cDovL2lfYW1fYV9saW5rIj5UaGlzIGlzIGEgbGluazwvYT4\u003d",
                "mime_type": "text/html"
              }
            ],
            "line": 96,
            "name": "the user is on the homepage",
            "match": {
              "location": "NavigationSteps.the_user_is_on_the_homepage()"
            },
            "keyword": "Given "
          }
        ],
        "tags": [
          {
            "line": 94,
            "name": "@DEV"
          }
        ]
      }
    ],
    "name": "Organisation - Overview",
    "description": "",
    "id": "organisation---overview",
    "keyword": "Feature",
    "uri": "organisation/Overview.feature",
    "tags": [
      {
        "line": 2,
        "name": "@ORGANISATION_OVERVIEW"
      }
    ]
  }
]`

**Comment by mpkorstanje** [comment] 2017-03-14 11:43
Ah. It appears that @damianszczepanik hasn't released 3.5.2 yet. This was fixed in d29bc20dd99f7f034334b1921e2cfe9a61f212b1.

**Comment by Ryxmedia** [comment] 2017-03-14 11:46
Great, so I'm going to wait for 3.5.2 then.
Thank you for the help :)

**Comment by damianszczepanik** [comment] 2017-03-14 22:43
Attach whole json file so I can confirm if this is fixed or not

**Comment by Ryxmedia** [comment] 2017-03-21 07:45
Working now with v 3.6.0.

**Comment by mayankporwal08** [comment] 2017-11-23 08:42
Hi damianszczepanik, I am also facing this issue on 3.12.0. Can you please help me fix this issue?

**Comment by mayankporwal08** [comment] 2017-11-24 08:35
[Test-report.zip](https://github.com/damianszczepanik/cucumber-reporting/files/1500995/Test-report.zip)

**Comment by damianszczepanik** [comment] 2017-11-26 21:55
Could not reproduce the problem

**Closed by damianszczepanik** 2017-11-26 21:55 UTC

**Comment by inel85** [comment] 2018-02-19 01:44
Hi damianszczepanik, I am also facing this issue on 3.14.0. Can you please help me fix this issue?
Issue only reproducible for scenario.write(). Scenario.embed() works fine.
I've attached the json file. 

[reproduced_3.14.0.zip](https://github.com/damianszczepanik/cucumber-reporting/files/1735379/reproduced_3.14.0.zip)

**Comment by damianszczepanik** [comment] 2018-02-25 21:49
This is because HTML links are in 'output' tag, not attachment. The output is displayed as it is and there is no magic here to determine if this is html or image.

**Comment by KPrathapReddy** [comment] 2019-10-17 10:43
> Ah. It appears that @damianszczepanik hasn't released 3.5.2 yet. This was fixed in [d29bc20](https://github.com/damianszczepanik/cucumber-reporting/commit/d29bc20dd99f7f034334b1921e2cfe9a61f212b1).

I am using cucumber reporting latest version 4.0. Still i can see that HTML tags are not interpreting in cucumber report. is there is solution for this problem.

**Comment by mpkorstanje** [comment] 2019-10-17 14:41
Yes, you can use:

```
String html = "....your html here....";
scenario.embed(html.getBytes(), "text/html");
```

**Comment by vikas-thange-efx** [comment] 2021-01-21 16:46
I see  scenario.embed() is deprecated. Can someone help with non deprecated alternative for doing same ?

**Comment by bothikarsk** [comment] 2021-06-14 17:29
I am using cucumber io 6.9.1 version. Html tags are not interpreted in html report. Any other alternative for doing same?

**Comment by damianszczepanik** [comment] 2021-06-22 20:07
http://damianszczepanik.github.io/cucumber-html-reports/overview-tags.html works fine

**Comment by bothikarsk** [comment] 2021-06-22 21:50
Well it work fine in cucumber masterthought report but doesn't work for html report generated in TestRunner class having CucumberOptions with pretty plugin (html:target/cucumber-reports/test-report.html)

**Comment by bothikarsk** [comment] 2021-06-22 21:57
![16243989066798013940086990186379](https://user-images.githubusercontent.com/47055500/123004809-c6fd1600-d3d2-11eb-9c50-69db0a2c1459.jpg)
Html tags are not interpreted.

**Comment by damianszczepanik** [comment] 2021-06-24 20:17
attach JSON report

**Comment by dashinghari6** [comment] 2022-04-06 17:26
Hi  am also facing the same issue 
Not able to attach html table to cucumber scenario

It is attached as normal text not as html even though I. Have the mime type as text/html

Cucumber version am using is 7.2.3

**Comment by dashinghari6** [comment] 2022-04-06 17:28
> ![16243989066798013940086990186379](https://user-images.githubusercontent.com/47055500/123004809-c6fd1600-d3d2-11eb-9c50-69db0a2c1459.jpg) Html tags are not interpreted.



Does this issue is resolved for you ?
