### ISSUE TITLE
Blocked script execution 

### ISSUE THREAD

**Issue by saadlu** [damianszczepanik/cucumber-reporting#281] opened 2016-01-02 20:10 UTC
After installing the plugin, I do not get to see the chart and the reports are not properly styled (table columns are not aligned or padded):

![screen](https://cloud.githubusercontent.com/assets/1028104/12075948/8182075c-b18c-11e5-8a2b-f2ee3c3273e5.png)

I also see errors on the console about loading the script. I am not an experienced webdev to understand these errors, any clues? Anything I should be doing?

**Comment by damianszczepanik** [comment] 2016-01-02 20:58
Duplicate of jenkinsci/cucumber-reports-plugin/issues/7

**Closed by damianszczepanik** 2016-01-02 20:58 UTC

**Comment by saadlu** [comment] 2016-01-03 22:26
yes it is. thanks
