### ISSUE TITLE
Empty Pie Charts with a lot of passed scenarios 

### ISSUE THREAD

**Issue by rommy1204** [damianszczepanik/cucumber-reporting#277] opened 2015-12-23 14:01 UTC
Hi guys,

We have noticed that svg element draws empty Pie Chart with a lot of passed scenarios / steps
![2015-12-23_1758](https://cloud.githubusercontent.com/assets/10895964/11977720/ef4931e8-a99e-11e5-87f2-97f1722d7088.png)
It is happened because of 199.999999 value here:

path fill="#88dd11" stroke="#ffffff" d="M200,150L199.99999892082684,270A120,120,0,1,1,200.00000107917316,270Z" stroke-width="1" stroke-linejoin="round" style="-webkit-tap-highlight-color: rgba(0, 0, 0, 0); stroke-linejoin: round;"></path

I've applied a sin where we replace "x1 = cx + r * Math.cos(-startAngle * rad)," to "x1 = cx + r * Math.cos(-startAngle * rad) - 1,"
so we have 198.9999999 here and it looks not perfect, but much better:
![2015-12-23_1800](https://cloud.githubusercontent.com/assets/10895964/11977749/248e83e4-a99f-11e5-9d00-5cc3c064705c.png)

Could you please fix this issue?

**Comment by damianszczepanik** [comment] 2015-12-24 09:56
Since you have data to reproduce and verify this case, how about sending pR with the patch?

**Comment by rommy1204** [comment] 2015-12-24 11:50
Hi, sure
You can try this one:
[cucumber.zip](https://github.com/damianszczepanik/cucumber-reporting/files/71700/cucumber.zip)

**Comment by damianszczepanik** [comment] 2016-01-07 22:54
Problem does not occur for Flash chars and for JS is caused by implementation which plugin uses: www.highcharts.com 

I will try to update and check if it helps.

**Comment by damianszczepanik** [comment] 2016-01-10 23:02
Fixed with last commit that upgrades mentioned library

**Closed by damianszczepanik** 2016-01-10 23:02 UTC
