### ISSUE TITLE
Cucumber Reports are not generating , getting the Below error. Please help me 

### ISSUE THREAD

**Issue by ManjunathMuniyapla** [damianszczepanik/cucumber-reporting#90] opened 2015-04-27 12:25 UTC
Oops Something went wrong with JOB_NAME build: 6

The error message (if any) is below:

org.apache.velocity.exception.MethodInvocationException: Invocation of method 'getRawName' in class net.masterthought.cucumber.json.Feature threw exception java.lang.NullPointerException at templates/featureOverview.vm[line 366, column 3

But i am seeing cucumber.json is created under workspace . 
and below is the cucumber plugin versions 
	
Cucumber json test reporting -- 0.7			
Cucumber Plugin -- 0.0.2			
cucumber-reports -- 0.0.24

**Comment by thomasmodeneis** [comment] 2015-04-30 14:23
I got the same error here.
It was ok on the version .23, so I'm now having to find the .hpi for version 23 and downgrade manually. :(

**Comment by thomasmodeneis** [comment] 2015-04-30 15:10
I've solved the problem downgrading to version 23.
Here is the link of it if you need.
http://www.masterthought.net/system/uploads/original_cucumber-reporting-0.0.23.jar

**Comment by damianszczepanik** [comment] 2015-05-03 10:30
@ManjunathMuniyapla can you attach json file ?

**Comment by AravindNalla** [comment] 2015-05-04 06:48
Thanks Thomas...downgrading solved issue.....

**Comment by tbutiu** [comment] 2015-05-15 08:04
Same here... Thank you.
Been trying 24 version, but fails. now downgrading back to 23.

**Comment by kingsleyh** [comment] 2015-05-15 08:06
I've just released version 0.1.0 - better to upgrade to that than downgrade I think

**Comment by tbutiu** [comment] 2015-05-15 08:10
Was just to say that, seen there's some changes 10-11 h ago.! 
Going to try it now! just to finish a batch of jobs... will come with feedback in short time!

Thank you for fast reply

**Comment by tbutiu** [comment] 2015-05-15 09:22
got this, now:
The error message (if any) is below:

org.apache.velocity.exception.MethodInvocationException: Invocation of method 'getFileName' in class net.masterthought.cucumber.json.Feature threw exception java.lang.NullPointerException at templates/featureOverview.vm[line 389, column 73]

Cucumber-JVM Jenkins Report Plugin - version: cucumber-reporting-0.1.0 - 15-05-2015 12:03:47

**Comment by kingsleyh** [comment] 2015-05-15 09:27
looks like a similar issue. @damianszczepanik do you have any idea about this?

**Comment by damianszczepanik** [comment] 2015-05-15 18:13
Basically there is something wrong with https://github.com/masterthought/cucumber-reporting/blob/master/src/main/java/net/masterthought/cucumber/json/Feature.java#L50 but it might be a problem to find out what without problematic json file...

Will take a look at this.

**Comment by damianszczepanik** [comment] 2015-05-16 10:48
@tbutiu 
I believe you are running tests parallel or have unusual configuration. Even I have assumption where the problem could happen without having json file I won't be able to reproduce it and - what is more important - confirm that issue is fixed.

Attach json file you are using or send me via email so I can cover it.

**Comment by tbutiu** [comment] 2015-05-18 06:38
Uploaded to google drive, can have a look here: https://drive.google.com/file/d/0B5YNKF7s81ihblE1WE1NamFKVEk/view?usp=sharing

File is too big ( 12M zip ) 
Have a look also on the screenshots, can they be added in the reporting, as a link/thumbnail exactly where's them set?

**Comment by damianszczepanik** [comment] 2015-05-22 21:04
@tbutiu 
I have fixed problem with screenshot in pull #106 and now they should be present for all status (previously only for FAILED while in your report status was undefined).

However I was not able to reproduce NullPointerException. Can you provide combination of the checkboxes (on/off) which you can configure over Jenkins for this plugin?

**Comment by tbutiu** [comment] 2015-05-25 06:20
The only checkbox enabled was for flash part...
screenshot here: http://screencast.com/t/455OctbGCf

**Comment by damianszczepanik** [comment] 2015-05-25 16:25
@tbutiu  you are using the old version of the plugin - upgrade the plugin and check again

**Comment by CanardSauvage** [comment] 2015-06-23 13:49
I have the problem with version 0.1.0 and I have the default configuration in jenkins. I could upload the cucumber.json and cucumber-dir from the target dir, would this help?

**Comment by damianszczepanik** [comment] 2015-06-23 21:48
It always does. Jon file and jenkins configuration should be enough

**Comment by slott** [comment] 2015-07-01 05:45
I'm having the exact same problem and getting this error message using latest version of the plugin:

org.apache.velocity.exception.MethodInvocationException: Invocation of method 'getFileName' in class net.masterthought.cucumber.json.Feature threw exception java.lang.NullPointerException at templates/featureOverview.vm[line 389, column 73]

**Comment by mvandervelden** [comment] 2015-08-14 11:19
I can confirm the issue. We have 3 jobs running Calabash tests. One of them is giving the exact same error message, the other ones are working just fine:
org.apache.velocity.exception.MethodInvocationException: Invocation of method 'getFileName' in class net.masterthought.cucumber.json.Feature threw exception java.lang.NullPointerException at templates/featureOverview.vm[line 389, column 73]

cucumber-reporting-0.1.0, default configuration.
Jenkins ver. 1.614
calabash-cucumber-0.14.3

**Comment by damianszczepanik** [comment] 2015-08-14 12:36
@mvandervelden I need to reproduce the issue and to make it happen I need json file. Please attach it.

**Comment by mvandervelden** [comment] 2015-08-17 09:03
I'm sorry, I updated the post to include a link to the output

**Comment by damianszczepanik** [comment] 2015-08-17 15:48
I've tried to reproduce the problem on Jenkins but it works fine. I have some idea so will try again later.

Sorry for the problem and thanks for the json file!

**Comment by damianszczepanik** [comment] 2015-08-18 20:17
Without success or rather it works fine so can you check to test your json file out of Jenkins just to eliminate influence of this tool? Take this code as example and let me know
https://github.com/damianszczepanik/cucumber-reporting/blob/master/README.md

Having no reproduction path it would be hard to fix AND confirm that fix is correct...

**Comment by mvandervelden** [comment] 2015-08-20 15:32
I tried replicating the error using your example code, and it's workingmen here too. So probably it's a Jenkins issue? Do you have any idea for a likely suspect/where to start looking? It seems like something in this particular job got messed up, I'll start by copying this job and see if I can replicate. I'll keep you updated if I find something interesting.

**Comment by damianszczepanik** [comment] 2015-08-20 15:45
Copy full logs from console of this failure execution (from Jenkin's job) - maybe that will help.

What is OS where Jenkins is running on?

**Comment by mthomas87** [comment] 2015-08-21 09:42
Had the same topic like @mvandervelden for weeks now. Until I recognized I have other .json files in my workspace which are compiled by the [CucumberReportPublisher] !
I fixed the problem with configuring the options in Jenkins, to give the explicit path and the files to compile!  (see screenshot) Because by default it browses your whole workspace for .json files.

![bildschirmfoto 2015-08-21 um 11 36 10](https://cloud.githubusercontent.com/assets/6641079/9405602/5505ca08-47f9-11e5-8fa0-da4aced61d2d.png)

Maybe this will fix it for you too! 
Cheers Martin

**Comment by mvandervelden** [comment] 2015-08-21 12:29
Thanks @mthomas87 . I was just converging to the same conclusion, but it definitely was the culprit.
Thank you all for your help.

**Comment by damianszczepanik** [comment] 2015-08-22 06:39
It's hard to detect if passed json file is a cucumber report or not. Instead I've added details into error page. Now list of json files are provided so you can easily verify if all passed files are cucumber reports or filter needs to be added to exclude invalid files:

![cucumber](https://cloud.githubusercontent.com/assets/9612911/9422888/3110ff7c-48a9-11e5-97c7-022ac8aadff5.png)

**Comment by damianszczepanik** [comment] 2015-08-22 06:41
@mthomas87 - good job!

Closing this issue, improvement will be released soom

**Closed by damianszczepanik** 2015-08-22 06:41 UTC

**Comment by harisharthanari** [comment] 2018-01-24 14:15
I receive similar message with ReportNG configured in my maven project
Does any one have any inputs to share?

[TestNG] Reporter org.uncommons.reportng.HTMLReporter@70e38ce1 failed
org.uncommons.reportng.ReportNGException: Failed generating HTML report.
at org.uncommons.reportng.HTMLReporter.generateReport(HTMLReporter.java:122)
at org.testng.TestNG.generateReports(TestNG.java:1184)
at org.testng.TestNG.run(TestNG.java:1109)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:177)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:105)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:103)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:74)
Caused by: org.apache.velocity.exception.MethodInvocationException: Invocation of method 'getUser' in class org.uncommons.reportng.ReportMetadata threw exception class java.net.UnknownHostException : ip-10-0-5-235: ip-10-0-5-235: Temporary failure in name resolution
at org.apache.velocity.runtime.parser.node.ASTIdentifier.execute(ASTIdentifier.java:193)
at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:175)
at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:220)
at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:230)
at org.apache.velocity.Template.merge(Template.java:256)
at org.apache.velocity.app.Velocity.mergeTemplate(Velocity.java:449)
at org.uncommons.reportng.AbstractReporter.generateFile(AbstractReporter.java:108)
at org.uncommons.reportng.HTMLReporter.createOverview(HTMLReporter.java:148)
at org.uncommons.reportng.HTMLReporter.generateReport(HTMLReporter.java:111)

**Comment by damianszczepanik** [comment] 2018-01-24 22:20
I have. Based on the stacktrace this problem has nothing common with this software, so please report the issue in correct place

**Comment by harisharthanari** [comment] 2018-01-25 13:32
Sure Damian. Sorry for the inconvenience
