### ISSUE TITLE
 Two cucubmer reports from Jenkins pipeline project with parallel testing stage

### ISSUE THREAD

**Issue by daveysa** [damianszczepanik/cucumber-reporting#732] opened 2018-06-12 21:16 UTC
Current I have the pipeline job running the system test  stage and can successfully get the "cucubmer reports" tag show on Jenkins. 

sample code below:
`
      stage ('System Testing'){
                    try {
                        sh './scripts/run-system-tests.sh'
                    } finally {
                        sh './scripts/clean-system-test-env.sh'
                    cucumber([
                                      jsonReportDirectory: './e2e-tests/features/output-files/reports',
                                      fileIncludePattern: 'reports.json',
                                      buildStatus: 'UNSTABLE'
                    ])
                    }
       }
 `

Now I need to test on different environemnt but with the same code, Is there a way to create two reports (e.g. "cucubmer reports Env A" and "cucubemr reports Env B"). I know for publishHTML it can set reportName and report title to pick different html file and generate report on jenkins with differnt tab (code below)
`
                        publishHTML([
                            allowMissing: false,
                            alwaysLinkToLastBuild: false,
                            keepAll: true,
                            reportDir: 'sample/output-files/',
                            reportFiles: 'report.html',
                            reportName: 'Reliability Report',     <---- can change name here
                            reportTitles: 'Reliability Report'     <----- can change name here
                        ])
`

Does cucumber report has the same functionality. My sample code will looks like below

`
      stage ('System Testing'){
         parallel(
              "Env A": {
                    try {
                        sh './scripts/run-system-tests-AAA.sh'
                    } finally {
                        sh './scripts/clean-system-test-env-AAA.sh'
                    cucumber([
                                      jsonReportDirectory: './e2e-tests/features/output-files/reports',
                                      fileIncludePattern: 'reports-AAA.json',
                                      buildStatus: 'UNSTABLE'
                    ])
                    }
             },
             "Env B": {
                    try {
                        sh './scripts/run-system-tests-BBB.sh'
                    } finally {
                        sh './scripts/clean-system-test-env-BBB.sh'
                    cucumber([
                                      jsonReportDirectory: './e2e-tests/features/output-files/reports',
                                      fileIncludePattern: 'reports-BBB.json',
                                      buildStatus: 'UNSTABLE'
                    ])
                    }
             }
       )
       }
 `

**Comment by damianszczepanik** [comment] 2018-06-18 20:39
Duplicate of https://github.com/jenkinsci/cucumber-reports-plugin/issues/237

**Closed by damianszczepanik** 2018-06-18 20:39 UTC
